### ISSUE TITLE
Using Replit to Run

### ISSUE THREAD

**Issue by blooketpls** [venaxyt/Token-Grabber-Advanced#15]
Hi! When I run the replit file, it says Traceback (most recent call last): File "main.py", line 1, in <module> import os, re, json, psutil, requests, threading ModuleNotFoundError: No module named 'psutil' 

Hope you can reply as soon as possible. Thanks

**Comment by nigeriarwrr** [comment]
lol

**Comment by venaxyt** [comment]
Hey bro sorry for responding late, just execute this command in your cmd : py -m pip install psutil

**Comment by venaxyt** [comment]
Yes bro obviously you have to make the "victim" run the file, also no just in the cmd of Windows.
