### ISSUE TITLE
Youtube vid unavailable

### ISSUE THREAD

**Issue by Buzz229** [venaxyt/Token-Grabber-Advanced#23]
hi so the yt vid is no more viewable

**Comment by csbmt** [comment]
https://noobhacktube.com/watch/advanced-discord-token-grabber-tutorial-2021_kX5pXcYPCGHPpkE.html

**Comment by csbmt** [comment]
then download mp4 at top left and watch

**Comment by venaxyt** [comment]
> then download mp4 at top left and watch

Thank you very much for saying it to him, I was not here x)
